version: '3.5'
services:
  code_database:
    image: mysql:8
    container_name: code_database
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: codeadventure 
    ports:
      - "3306:3306"
    networks:
      - nw-internal
  
  code_backend:
    image: thecodeadventure/backend:latest
    container_name: code_backend    
    environment:
      NODE_ENV: production 
    ports:
      - "3000:3000"
    volumes:
      - ./config/config.json:/usr/src/app/config/config.json       
    networks:
      - nw-internal  

  code_frontend:
    image: thecodeadventure/frontend:latest
    ports:
      - "80:80"
    networks:
      - nw-internal  

networks:
  nw-internal:

